export {default as LoginPage } from './LoginPage'
export {default as RegisterPage } from './RegisterPage'
export {default as HomePage } from './HomePage'
export {default as CartPage } from './CartPage'
export {default as ProductPage } from './ProductPage'
export {default as MedicinePage } from './MedicinePage'
export {default as MedicineStorePage } from './MedicineStorePage'